import { Course, SchedulePlan } from '../types/schedule';
import { getAccessToken } from './auth';

// Maps arbitrary hex to nearest Google Calendar colorId
// 1: Lavender, 2: Sage, 3: Grape, 4: Flamingo, 5: Banana, 6: Tangerine
// 7: Peacock, 8: Graphite, 9: Blueberry, 10: Basil, 11: Tomato
const GOOGLE_CALENDAR_COLORS = [
  { id: '1', hex: '#7986cb', r: 121, g: 134, b: 203 },
  { id: '2', hex: '#33b679', r: 51, g: 182, b: 121 },
  { id: '3', hex: '#8e24aa', r: 142, g: 36, b: 170 },
  { id: '4', hex: '#e67c73', r: 230, g: 124, b: 115 },
  { id: '5', hex: '#f6c026', r: 246, g: 192, b: 38 },
  { id: '6', hex: '#f5511d', r: 245, g: 81, b: 29 },
  { id: '7', hex: '#039be5', r: 3, g: 155, b: 229 },
  { id: '8', hex: '#616161', r: 97, g: 97, b: 97 },
  { id: '9', hex: '#3f51b5', r: 63, g: 81, b: 181 },
  { id: '10', hex: '#0b8043', r: 11, g: 128, b: 67 },
  { id: '11', hex: '#d60000', r: 214, g: 0, b: 0 },
];

function getClosestGoogleColorId(hexColor?: string): string {
  if (!hexColor) return '9'; // default to Blueberry (similar to our indigo/blue default)
  const hex = hexColor.replace('#', '');
  const r = parseInt(hex.substring(0, 2), 16);
  const g = parseInt(hex.substring(2, 4), 16);
  const b = parseInt(hex.substring(4, 6), 16);

  let bestId = '9';
  let bestDist = Infinity;
  for (const gc of GOOGLE_CALENDAR_COLORS) {
    const dr = r - gc.r;
    const dg = g - gc.g;
    const db = b - gc.b;
    const dist = Math.sqrt(dr * dr + dg * dg + db * db);
    if (dist < bestDist) {
      bestDist = dist;
      bestId = gc.id;
    }
  }
  return bestId;
}

const DAY_MAP: Record<string, { jsDay: number; icsDay: string }> = {
  monday: { jsDay: 1, icsDay: 'MO' },
  tuesday: { jsDay: 2, icsDay: 'TU' },
  wednesday: { jsDay: 3, icsDay: 'WE' },
  thursday: { jsDay: 4, icsDay: 'TH' },
  friday: { jsDay: 5, icsDay: 'FR' },
  saturday: { jsDay: 6, icsDay: 'SA' },
  sunday: { jsDay: 0, icsDay: 'SU' },
};

function getFirstDayOccurrence(startDate: Date, targetJsDay: number): Date {
  const current = new Date(startDate.getFullYear(), startDate.getMonth(), startDate.getDate());
  const currentDay = current.getDay();
  let diff = targetJsDay - currentDay;
  if (diff < 0) diff += 7;
  current.setDate(current.getDate() + diff);
  return current;
}

function parseLocalDate(dateStr: string): Date {
  if (!dateStr) return new Date();
  const parts = dateStr.split('-');
  if (parts.length === 3) {
    return new Date(parseInt(parts[0]), parseInt(parts[1]) - 1, parseInt(parts[2]));
  }
  return new Date(dateStr);
}

function createIsoDateTime(date: Date, timeStr: string): string {
  const [hh, mm] = timeStr.split(':').map(Number);
  const dt = new Date(date);
  dt.setHours(hh, mm, 0, 0);
  return dt.toISOString();
}

function formatIcsUntil(date: Date): string {
  const y = date.getUTCFullYear();
  const m = String(date.getUTCMonth() + 1).padStart(2, '0');
  const d = String(date.getUTCDate()).padStart(2, '0');
  return `${y}${m}${d}T235959Z`;
}

export async function syncScheduleToGoogleCalendar(
  plan: SchedulePlan,
  semesterStart: string,
  semesterEnd: string,
  onProgress?: (msg: string) => void
) {
  const token = await getAccessToken();
  if (!token) throw new Error('Not authenticated with Google');

  const startDate = parseLocalDate(semesterStart);
  const endDate = parseLocalDate(semesterEnd);
  const untilStr = formatIcsUntil(endDate);

  if (onProgress) onProgress('Creating calendar...');

  // Create a new calendar for the schedule to keep it isolated
  const calRes = await fetch('https://www.googleapis.com/calendar/v3/calendars', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      summary: `${plan.name || 'My Schedule'} - Uniplan`,
      description: 'Course schedule generated by Uniplan',
      timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
    }),
  });

  if (!calRes.ok) {
    throw new Error('Failed to create calendar');
  }

  const calendarData = await calRes.json();
  const calendarId = calendarData.id;

  if (onProgress) onProgress('Adding courses...');

  const courses = plan.courses || [];
  
  for (const course of courses) {
    if (!course.sessions || course.sessions.length === 0) continue;
    
    const colorId = getClosestGoogleColorId(course.color);
    
    for (const session of course.sessions) {
      const dayInfo = DAY_MAP[session.day];
      if (!dayInfo) continue;
      
      const firstSessionDate = getFirstDayOccurrence(startDate, dayInfo.jsDay);
      // Skip if the first session happens after the semester ends
      if (firstSessionDate.getTime() > endDate.getTime()) continue;
      
      const startIso = createIsoDateTime(firstSessionDate, session.startTime || '09:00');
      const endIso = createIsoDateTime(firstSessionDate, session.endTime || '10:00');
      
      const codeSec = course.section ? `${course.code}-${course.section}` : course.code;
      const title = `${codeSec} ${course.name}`.trim();
      
      const descParts: string[] = [];
      if (course.instructor) descParts.push(`Instructor: ${course.instructor}`);
      if (course.credits) descParts.push(`Credits: ${course.credits}`);
      
      const eventData = {
        summary: title,
        location: session.room || '',
        description: descParts.join('\n'),
        colorId, // The closest Google Calendar color index!
        start: {
          dateTime: startIso,
          timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
        },
        end: {
          dateTime: endIso,
          timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
        },
        recurrence: [
          `RRULE:FREQ=WEEKLY;UNTIL=${untilStr};BYDAY=${dayInfo.icsDay}`
        ]
      };
      
      await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(eventData),
      });
    }
  }
  
  if (onProgress) onProgress('Sync complete!');
  return calendarId;
}
